// 노트북/React/news/src/components/ask_view/ask_view.jsx
import React, { useEffect, useState } from 'react';
import { fetchAsksList } from '../../api';

const AskView = (props) => {
    let [ask , setAsk] = useState([]);

    useEffect(()=>{
        fetchAsksList()
            .then((respone)=>setAsk(respone.data))
            .catch((error)=>console.log(error))
    },[])

    return (
        <div>
            {ask.map((ask)=>(<div key={ask.id}>{ask.title}</div>))}
        </div>
    )
};

export default AskView;

// Vue/vue-news/src/views/AskView.vue
<template>
    <div>
        <div v-for="ask in ask" v-bind:key="ask.id">{{ ask.title }}</div>
    </div>
</template>

<script>
import { fetchAskList } from "../api/index.js";
export default {
    data(){
        return {
            ask : []
        }
    },
    created(){
        let vm = this;
        fetchAskList()
            .then(function(responsive){
                vm.ask = responsive.data
            })
            .catch(function(error){
                console.log(error);
            })
    }
}
</script>

<style>

</style>
