// 노트북/React/news/src/components/news_view/news_view.jsx
import React, { useState , useEffect } from 'react';
// import axios from 'axios';
import { fetchNewsList } from '../../api/index.js';

const NewsView = (props) => {
    const [news, setNews] = useState([]);
    useEffect(() => {
        
    // case.01 fecth
    // const requestOptions = {
    //     method: 'GET',
    //     redirect: 'follow'
    // };
    // fetch("https://api.hnpwa.com/v0/news/1.json", requestOptions)
    //     .then(response => response.json())
    //     .then(result => {
    //         // console.log(result);
    //         setNews(result)
    //         console.log(news);
    //     })
    //     .catch(error => console.log('error', error));

    // case.01 axios
        fetchNewsList()
            .then((respone)=>{
                // console.log(respone);
                setNews(respone.data)
                // console.log(news);
            })
            .catch(function(error){
                console.log(error);
            });
    }, [])
        
    return (
        <div>
            news {news.map((news)=> (<div key={news.id}>{news.title}</div>))}
        </div>
    )    
};

export default NewsView;

// Vue/vue-news/src/views/NewsView.vue
<template>
    <div>
        <div v-for="user in users" v-bind:key="user.id">{{ user.title }}</div>
    </div>
</template>

<script>
// import axios from 'axios';
import { fetchNewsList } from '../api/index.js'
export default {
    data() {
        return{
            users : []
        }
    },
    created() {
        let vm = this;
        // axios.get('https://api.hnpwa.com/v0/news/1.json')
        fetchNewsList()
            .then(function(response){
                console.log(response);
                vm.users = response.data;
            })
            .catch(function(error){
                console.log(error);
            })
    }
}
</script>

<style>

</style>
