// 노트북/React/news/src/components/ask_view/ask_view.jsx
import axios from 'axios';
import React, { useEffect, useState } from 'react';

const AskView = (props) => {
    let [ask , setAsk] = useState([]);

    useEffect(()=>{
        axios.get('https://api.hnpwa.com/v0/ask/1.json')
            .then((respone)=>setAsk(respone.data))
            .catch((error)=>console.log(error))
    },[])

    return (
        <div>
            {ask.map((ask)=>(<div key={ask.id}>{ask.title}</div>))}
        </div>
    )
};

export default AskView;

// 노트북/Vue/news/src/views/AskView.vue
<template>
    <div>
        <div v-for="ask in ask" v-bind:key="ask.id">{{ ask.title }}</div>
    </div>
</template>

<script>
import axios from 'axios';
export default {
    data(){
        return {
            ask : []
        }
    },
    created(){
        const vm = this;
        axios.get('https://api.hnpwa.com/v0/ask/1.json')
            .then((respone)=>{
                console.log(respone);
                vm.ask = respone.data
            })
            .catch(function(error){
                console.log(error)
            })
    }
}
</script>

<style>

</style>
