// Vue/vue-news/src/views/UserView.vue
<template>
    <div>
        <p>name : {{ userInfo.id }}</p>
        <p>karma : {{ userInfo.karma }}</p>
        <p>created : {{ userInfo.created }}</p>
        <!-- <p>{{ this.$store.state.user.about }}</p> -->
    </div>
</template>

<script>
// import axios from 'axios';

export default {
    computed : {
        userInfo(){
            return this.$store.state.user;
        }
    },
    created(){
        // console.log(this.$route.params.id);
        const userName = this.$route.params.id
        // axios.get(`https://api.hnpwa.com/v0/user/${userName}.json`);
        this.$store.dispatch('FETCH_USER' , userName);
    }
}
</script>

<style>

</style>

// 노트북/React/news/src/components/user_view/user_view.jsx
import axios from 'axios';
import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';

const UserView = (props) => {
    const [user , setUser] = useState([]);

    let params = useParams();

    useEffect(()=>{
        axios.get(`https://api.hnpwa.com/v0/user/${params.userName}.json`)
            .then(({data})=>{
                setUser(data)
            })
            .catch((error)=>console.log(error))
    },[]);

    return(
        <div>
            <p>name : {user.id}</p>
            <p>karma : {user.karma}</p>
            <p>created : {user.created}</p>
        </div>
    )
};

export default UserView;
