// 노트북/Vue/news/src/views/JobsView.vue
<template>
    <div>
        <div v-for="job in jobs" v-bind:key="job.id">{{ job.title }}</div>
    </div>
</template>

<script>
import axios from 'axios';
export default {
    data() {
        return {
            jobs : []
        }
    },
    created(){
        const vm = this;
        axios.get('https://api.hnpwa.com/v0/jobs/1.json')
            .then((respone)=>{
                console.log(respone);
                vm.jobs = respone.data;
            })
            .catch(function(error){
                console.log(error);
            })
    }
}
</script>

<style>

</style>

// 노트북/React/news/src/components/jobs_view/jobs_view.jsx
import axios from 'axios';
import React, { useEffect, useState } from 'react';


const JobsView = (props) => {
    let [jobs , setJobs] = useState([])

    useEffect(()=>{
        axios.get('https://api.hnpwa.com/v0/jobs/1.json')
            .then((respone)=>{
                // console.log(respone);
                setJobs(respone.data)
            })
            .catch((error)=>console.log(error))
    },[])

    return(
        <div>
            {jobs.map((jobs)=><div key={jobs.id}>{jobs.title}</div>)}
        </div>      
    )
};

export default JobsView;
