// Vue/vue-news/src/views/JobsView.vue
<template>
    <div>
        <div v-for="job in jobs" v-bind:key="job.id">{{ job.title }}</div>
    </div>
</template>

<script>
import { fetchJobsList } from '../api/index.js'
export default {
    data() {
        return{
            jobs : []
        }
    },
    created(){
        // let vm = this;
        fetchJobsList()
            .then(response =>{
                console.log(response);
                this.jobs = response.data;
            })
            .catch(function(error){
                console.log(error);
            });
    }
}
</script>

<style>

</style>

// 노트북/React/news/src/components/jobs_view/jobs_view.jsx
import React, { useEffect, useState } from 'react';
import { fetchJobsList } from '../../api';

const JobsView = (props) => {
    let [jobs , setJobs] = useState([])

    useEffect(()=>{
        fetchJobsList()
            .then((respone)=>{
                // console.log(respone);
                setJobs(respone.data)
            })
            .catch((error)=>console.log(error))
    },[])

    return(
        <div>
            {jobs.map((jobs)=><div key={jobs.id}>{jobs.title}</div>)}
        </div>      
    )
};

export default JobsView;
