// 노트북/React/youtube/src/components/searchForm/searchForm.jsx
import React ,{ useRef } from 'react';
import './searchForm.css'

const SearchForm = () => {
    let searchText = useRef();
    let searchValue ='';
    function searchClick(){
        searchValue = searchText.current.value;
        console.log(searchValue);
        searchValue = '';
    }

    function keyEvent(e){
        // console.log(e.key);
        if(e.key === 'Enter'){
            searchClick();
        }
    }
    
    return (
        <div className='searchArea'>
            <input type="text" ref={searchText} onKeyDown={keyEvent}/>
            <button onClick={searchClick}>
                <span className="material-icons-outlined">
                    search
                </span>
            </button>
        </div>
    );
};

export default SearchForm;

// 노트북/Vue/youtube/src/components/searchForm.vue
<template>
    <div>
        <input type="text" v-model="searchText" v-on:keyup.enter="searchClick">
        <button v-on:click="searchClick">
            <span class="material-icons-outlined">
                search
            </span>
        </button>
    </div>
</template>

<script>
export default {
    data () {
        return {
            searchText : ''
        }
    },
    methods: {
        searchClick() {
            // console.log(this.searchText);
            if(this.searchText !== ''){
                this.$emit('searchFun', this.searchText);
                this.searchText = '';
            }
        }
    },


}
</script>

<style scoped>
    div{display: flex; justify-content: center; margin-bottom: 20px;}
    div input{width: 50%; height: 30px; border: 1px solid black;}
    div button{width: 30px; height: 30px; font-size: 30px;}
</style>
