// 노트북/React/youtube/src/components/videoItem/videoItem.jsx
import React from 'react';
import './videoItem.css';
import { useNavigate } from 'react-router-dom';

const VideoItem = (props) => {
    const navigate = useNavigate();
    return <li onClick={()=>{
        navigate('/test' , 'test');
    }}>
        <img src={props.video.snippet.thumbnails.medium.url} alt="" />
        <p>{ props.video.snippet.title }</p>
    </li>
};

export default VideoItem;

// 노트북/Vue/youtube/src/components/videoItem.vue
<template>
    <div>
        <!-- <ul>
            <li v-for="youtubeData in this.youtubeData" v-bind:key="youtubeData.id">
                <h2>{{ youtubeData.snippet.title}}</h2>
                <img v-bind:src="youtubeData.snippet.thumbnails.medium.url" alt="video thumbnail">
            </li>
        </ul> -->
    </div>
</template>

<script>


export default {
       
}
</script>

<style>

</style>
